vlib work
vlog  node_aut.v
vlog  NA1_SA.v
vlog  node_aut_block.v
vlog  NA2_AV.v
vlog  node_aut_block1.v
vlog  NA3_RV.v
vlog  NA4_F1.v
vlog  NA5_F2.v
vlog  node_aut_block2.v
vlog  NA6_S1.v
vlog  NA7_S2.v
vlog  path_aut.v
vlog  PA1_1to2.v
vlog  path_aut_block.v
vlog  PA2_2to3.v
vlog  path_aut_block1.v
vlog  PA3_1to4.v
vlog  path_aut_block2.v
vlog  PA4_1to6.v
vlog  path_aut_block3.v
vlog  PA5_4to5.v
vlog  path_aut_block4.v
vlog  PA6_6to7.v
vlog  path_aut_block5.v
vlog  PA7_5to7.v
vlog  PAC.v
vlog  case2mod_new.v
